name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Commitlint and Husky
        run: |
          npm install --global @commitlint/{config-conventional,cli}
          npm install --global husky

      - name: Lint commit messages
        run: |
          npx commitlint --from=HEAD~1 --to=HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
