name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Commitlint and Husky
        run: |
          npm install --global @commitlint/{config-conventional,cli}
          npm install --global husky

      - name: Get Previous Commit
        id: get-commit
        run: |
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            echo "HAS_PREV_COMMIT=true" >> $GITHUB_ENV
          else
            echo "HAS_PREV_COMMIT=false" >> $GITHUB_ENV
          fi

      - name: Lint commit messages
        if: env.HAS_PREV_COMMIT == 'true'
        run: |
          npx commitlint --from=HEAD~1 --to=HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No Previous Commit
        if: env.HAS_PREV_COMMIT == 'false'
        run: echo "No previous commit found. Skipping linting."
