name: Cppcheck

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          args: --enable=all --inconclusive

