name: kernel build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache CMake files
      id: cache-cmake
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/build
        key: cmake-build-${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ github.sha }}
        restore-keys: |
          cmake-build-${{ runner.os }}-${{ env.BUILD_TYPE }}-

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/lunix -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
